### ISSUE TITLE
最新的课件地址

### ISSUE THREAD

**Issue by xxlyu-2046** [Fafa-DL/Lhy_Machine_Learning#7]
repo里的课件不是最新的，和视频里有差别。最新的课件直接在课程官网下载：https://speech.ee.ntu.edu.tw/~hylee/ml/2021-spring.html

**Comment by Fafa-DL** [comment]
我就是在课程官网当时同步下载的课件呀

**Comment by xxlyu-2046** [comment]
> 我就是在课程官网当时同步下载的课件呀

不一样，比如GAN 官网版本：https://speech.ee.ntu.edu.tw/~hylee/ml/ml2021-course-data/gan_v10.pdf，repo里的是v9

**Comment by Fafa-DL** [comment]
奥奥可能做了更新，我当时第一时间同步下载的版本是v9版本，谢谢啦。

**Comment by xxlyu-2046** [comment]
不客气~
